In [2]:
import numpy as np

### creating simple array

In [7]:
# one dimention array
a=np.array([1,2,3])
# multi dimention array
b=np.array([[2,4,2],[5,2,4]])
print('this is one dimention array : \n',a) 
print('this is multi dimention array : \n',b) 

this is one dimention array : 
 [1 2 3]
this is multi dimention array : 
 [[2 4 2]
 [5 2 4]]


### basic info

In [11]:
# finding the shape of matrix 
print(a.shape)
print(b.shape)

(3,)
(2, 3)


### reshape the matrix

In [21]:
reshaped_a=a.reshape(3,1)
print(reshaped_a.shape)


reshaped_b=b.reshape(3,2)
print(reshaped_b.shape)

(3, 1)
(3, 2)


### if we dont know the shape and want to reshape just add -1 

In [24]:
unknown_reshape=b.reshape(-1,3)
unknown_reshape.shape

(2, 3)

### concatenate

In [52]:
a = np.array([[3, 5], [6, 2]])
b = np.array([[7, 11]])
add_to_row=np.concatenate((a,b),axis=0)
add_to_col=np.concatenate((a,b.T),axis=1)
print(add_to_row)
print('\n')
print(add_to_col)


[[ 3  5]
 [ 6  2]
 [ 7 11]]


[[ 3  5  7]
 [ 6  2 11]]


### Mathmathic operation 

 add a(n,n) to b(n,b)=c(n,n)

In [55]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b
print(c)

[5 7 9]


add a(1,n) or a(n,1) to b(n,m)=c(n,m)  


In [58]:
a=np.array([1])
b=np.array([1,2,3])
c=a+b
print(c)

# for more details check numpy doc and search about broadcusting 

[2 3 4]


#### create array from scratch

In [63]:
# making an array of 0s 
a=np.zeros((3,4))
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [66]:
# making array of 1s
a=np.ones((3,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [70]:
# making an array of random number
a=np.random.random((2,3))
a

array([[0.45806595, 0.53364462, 0.96083882],
       [0.46932017, 0.93370366, 0.43631116]])

In [73]:
# making an array that starts from zero and end to specific number
a=np.indices((4,3))
a


array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [81]:
# making an array of random integer number
#np.random.randint(start,stop,size)
a=np.random.randint(3,30,10)
a

array([24,  9, 25,  4, 20, 12, 21, 21, 22,  3])

In [16]:
# using linspace 
# np.linspace(start,stop,size)
a=np.linspace(0,1,6)
a


array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

linear algebra arrays

In [19]:
a=np.eye(3)
b=np.diag([1,2,3])

print(a,"\n")
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1 0 0]
 [0 2 0]
 [0 0 3]]


### joining arrays

join using stack

In [33]:
a=np.ones((3,2))
b=np.zeros((3,2))
np.stack((a,b),axis=1)

array([[[1., 1.],
        [0., 0.]],

       [[1., 1.],
        [0., 0.]],

       [[1., 1.],
        [0., 0.]]])

In [36]:
d=np.vstack((a,b))
d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
f=np.hstack((a,b))
f

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])